config/routes.rb
Rails.application.routes.draw do
  # application resources
  resources :number_records

  # devise routes
  devise_for :users

  root "number_records#index"
end

app/models/number_record.rb
class NumberRecord < ActiveRecord::Base
  validates :value, inclusion: { in: 1..10 }
  validates :value, numericality: { only_integer: true}
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/number_records_controller.rb
class NumberRecordsController < ApplicationController
  before_action :set_number_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /number_records
  # GET /number_records.json
  def index
    @number_records = NumberRecord.all
  end

  # GET /number_records/1
  # GET /number_records/1.json
  def show
  end

  # GET /number_records/new
  def new
    @number_record = NumberRecord.new
  end

  # GET /number_records/1/edit
  def edit
  end

  # POST /number_records
  # POST /number_records.json
  def create
    @number_record = NumberRecord.new(number_record_params)

    respond_to do |format|
      if @number_record.save
        format.html { redirect_to number_records_path, notice: 'Number record was successfully created.' }
        format.json { render :show, status: :created, location: @number_record }
      else
        format.html { render :new }
        format.json { render json: @number_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /number_records/1
  # PATCH/PUT /number_records/1.json
  def update
    respond_to do |format|
      if @number_record.update(number_record_params)
        format.html { redirect_to @number_record, notice: 'Number record was successfully updated.' }
        format.json { render :show, status: :ok, location: @number_record }
      else
        format.html { render :edit }
        format.json { render json: @number_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /number_records/1
  # DELETE /number_records/1.json
  def destroy
    @number_record.destroy
    respond_to do |format|
      format.html { redirect_to number_records_url, notice: 'Number record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number_record
      @number_record = NumberRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_record_params
      params.require(:number_record).permit(:value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/number_records_helper.rb
module NumberRecordsHelper
end

app/views/layouts/_navbar.html.erb
<div id='navbar'>
  <div id='navbar-text'>
    <% if user_signed_in? %>
    Welcome <%= current_user.email %>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <% else %>
      Welcome Guest!
    <% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cole Faloon's NumberCRUD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>
</html>

app/views/number_records/_form.html.erb
<%= form_for(@number_record) do |f| %>
  <% if @number_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number_record.errors.count, "error") %> prohibited this number_record from being saved:</h2>

      <ul>
      <% @number_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/number_records/edit.html.erb
<h1>Editing Number Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @number_record %> |
<%= link_to 'Back', number_records_path %>

app/views/number_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Number Records</h1>
<% data_hash = {} %>
<% (1..10).each { |n| data_hash[n] = 0 } %>
<% data_hash.merge!(NumberRecord.group(:value).count) %>
<% chart_options =  { xtitle: "NumberRecord Value", ytitle: "Count", curve: false,
                      label: 'Count'} %>
<% library_options = { scales:
                       { yAxes: [{ticks: { max: data_hash.max_by{ |k,v| v }.second,
                                           min: 0, stepSize: 1 }}]}} %>
<% chart_options[:library] = library_options %>

<%= line_chart data_hash, chart_options %>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        
    <% @number_records.each do |number_record| %>
      <tr>
        <td><%= number_record.value %></td>
        <td><%= link_to 'Destroy', number_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number record', new_number_record_path %>

app/views/number_records/new.html.erb
<h1>New Number Record</h1>

<%= render 'form' %>

<%= link_to 'Back', number_records_path %>

app/views/number_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @number_record.value %>
</p>

<%= link_to 'Edit', edit_number_record_path(@number_record) %> |
<%= link_to 'Back', number_records_path %>